name: Build
on:
  pull_request: {}
  merge_group:
    types: [checks_requested]
  push: {}
jobs:
  build:
    runs-on: ubuntu-latest
    name: Build binaries
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: git fetch --force --tags
      - uses: actions/setup-go@v4
        with:
          go-version: "1.23"
      - uses: goreleaser/goreleaser-action@v4
        with:
          distribution: goreleaser
          version: latest
          args: build --clean --snapshot
      - run: dist/fritzbox-client_linux_amd64_v1/fritzbox-client --help
